### ISSUE TITLE
Plans on vue-gesture

### ISSUE THREAD

**Issue by wobsoriano** [mlyknown/vue-gesture#10]
Hi,

Do you have any plans for `vue-gesture`? I was planning on using the package name for [use-gesture](https://github.com/wobsoriano/use-gesture).

Let me know what I can do if you're ready to sunset it.

Thank you!

**Comment by mlyknown** [comment]
No plans ! So what can I do something?

**Comment by wobsoriano** [comment]
If it's not maintained anymore and you're willing to let me use the package `vue-gesture` that would be awesome! I'll credit you in the README of the library.

You can do `npm unpublish vue-gesture --force`.

**Comment by mlyknown** [comment]
OK! Vue-gesture has been deprecated. can you use the package vue-gesture now?

**Comment by wobsoriano** [comment]
It should be usable after 24 hours. It's not in npm anymore so I will be able to publish after 24 hours. Thank you!

I'll add you to the project's README 😃

**Comment by mlyknown** [comment]
OK！ If has any question, please contract me. Good luck with your work!
