### ISSUE TITLE
priority is deprecated in vue 2.x

### ISSUE THREAD

**Issue by hs3180** [mlyknown/vue-gesture#2]
see http://vuejs.org/guide/migration.html#Custom-Directives

> Options such as acceptStatement, deep, **_priority_**, etc are all deprecated. To replace twoWay directives, see this example.

**Comment by ghjagus** [comment]
error:
vue-gesture.js:274 Uncaught TypeError: Cannot read property 'priority' of undefined
i use vue2

**Comment by mlyknown** [comment]
建议使用官方的手势插件（因为当时以为官方没有手势插件才写的这个插件的，仅仅支持 1.0+）
2.0 官方下载      npm install --save git://github.com/vuejs/vue-touch.git#next
