### ISSUE TITLE
使用报错,作者是不是不打算维护这个了

### ISSUE THREAD

**Issue by youdianfan** [mlyknown/vue-gesture#6]
![snipaste_2017-12-21_11-32-30](https://user-images.githubusercontent.com/27018910/34239498-ae56b84e-e642-11e7-979e-b18323073d9d.png)
Uncaught TypeError: Cannot read property 'priority' of undefined

**Comment by bees4ever** [comment]
Are you using VueJs version 2 or version 1. This plugin is for version 1, I made a fork to try to get this work under vuejs 2. You can see it here: https://github.com/bees4ever/vue2-gesture.

**Comment by mlyknown** [comment]
Sorry,this isn't support VueJS2.0, You can use https://github.com/bees4ever/vue2-gesture or https://github.com/vuejs/vue-touch.git

**Comment by mlyknown** [comment]
@bees4ever  Sorry,I forget this.I will publish later.

**Comment by bees4ever** [comment]
@mlyknown no problem :D
