### ISSUE TITLE
it's tap instead of tab

### ISSUE THREAD

**Issue by sjoerdloeve** [mlyknown/vue-gesture#7]
Readme says to use `tab`, but that does not work.
When I use `tap` it works correct so I think it's just a typo in the readme page?

In readme and not working:
`<vue-gesture :type="'tab'"  :call="handleComponent.bind(this,'tab')" >tap</vue-gesture>`

Working:
`<vue-gesture :type="'tap'"  :call="handleComponent.bind(this,'tap')" >tap</vue-gesture>`

Also cool to know for people who don't:
`<vue-gesture :type="'tap'"  :call="() => { changeProperty = true}" >tap</vue-gesture>`

**Comment by bees4ever** [comment]
Hi @sjoerdloeve,
thank you for your message. Sorry, for the typo... 🙈  I will change it soon.

**Comment by bees4ever** [comment]
I close it, maybe reopen it / make a new for other issues. 
Thanks
